### ISSUE TITLE
No sftp support?

### ISSUE THREAD

**Issue by devhell** [rustic-rs/rustic_core#11]
Hi!

Love the project, thank you so much! When I tried to use my existing restic repository (Hetzner Storagebox), rustic lets me know that the sftp backend is not supported. Am I missing something? :)

Thank you :D

**Comment by jirutka** [comment]
That’s a really unpleasant finding. I had no idea that rustic didn’t support SSH transport, I took it for granted. I preferred rustic over restic because I really don’t like Go, so rclone is not an option – it’s bloated af.

**Comment by aawsome** [comment]
@jirutka See #73 which is currently under review. sftp will be supported via opendal. When #73 is merged we'll make a new rustic_core release and soon after a new rustic release.

Also looking forward to feedback if you are able to self-compile with that PR (Note: for rustic, you should also use https://github.com/rustic-rs/rustic/pull/977).
