### ISSUE TITLE
Implement verification of blobs before uploading

### ISSUE THREAD

**Issue by duracell** [rustic-rs/rustic_core#153]
**Introduction:**
Recently, users have encountered issues with corrupted data when using the "max" compression feature in the (go) tool restic. These instances of data corruption can lead to data loss and other complications, highlighting the need for a robust identification of such errors beside the fix itself to detect similar bugs. The PR of restics solution is linked below.

**Explanation of the Feature:**
The proposed feature involves implementing this blob verification before uploading data. This process would detect errors and inconsistencies in the data, preventing corrupted data from being uploaded to the repository. By performing verification checks prior to uploading, rustic can ensure the integrity of stored data and provide users with greater confidence in their backups. Today a corruption is not detectable until the user runs the "read-data" command, which may not that often or sometimes never.

As mentioned in the discussion: I would be nice "to have this as optional feature which can switched on using CLI options or the config file." I personally would suggest a default activation would be great, because on a backup solution security and verification should be the default.

**Benefits:**
* Prevents data loss by detecting errors before they are uploaded to the repository.
* Provides early detection of data corruption, allowing users to take corrective actions promptly.
* Saves bandwidth by avoiding the upload of corrupted data.

**Disadvantages:**
Possible disadvantage mentioned in the rustic discussion (linked below):
> I think the implementation would be not too hard, but might slow down backup runs a bit...

**References:**
* [Discussion on rustic repo](https://github.com/rustic-rs/rustic/discussions/1049)
* [Restic Forum post about the problem](https://forum.restic.net/t/check-reports-errors-wrong-data-returned/7201/7)
* [Github PR of restic](https://github.com/restic/restic/pull/4681)

---
Hope this is written well enough, thank you for your great work and fast support! <3

**Comment by aawsome** [comment]
Thanks a log @duracell 
I have already proposed a (draft) PR - see #154. As said the implementation of the check is the smallest part. We will have to take a little more time to answer the architectural and strategical open questions ;-)

**Comment by duracell** [comment]
That's fast! Thanks! Take all the time you need. It should be improve integrity and not open bugs ;)
