### ISSUE TITLE
`rustic copy --init` should ask for the destination password

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/rustic_core#161]
Note that `rustic copy --init` still doesn't ask for the destination password when initializing the destination repository (and it is not specifed).
To implement this, we need more rustic_core support...

_Originally posted by @aawsome in https://github.com/rustic-rs/rustic/issues/1061#issuecomment-1939784367_

**Comment by aawsome** [comment]
Actually realized that the `init_with_config` method already supports giving a password directly. So this can be solved solely within rustic, see https://github.com/rustic-rs/rustic/pull/1063
