### ISSUE TITLE
Unhelpful error types

### ISSUE THREAD

**Issue by drdo** [rustic-rs/rustic_core#230]
As an example, when opening a `Repository` if the host cannot be found we get only a `ListingRepositoryConfigFileFailed` with no indication as to why this happened.

It would be nice if this type included information about the upstream errors that caused this (in this case probably `opendal::Error` at least).

**Comment by simonsan** [comment]
I agree, the whole error handling situation is a bit cumbersome at this point and a rework is needed with the above-mentioned improvements. 👍🏽

**Comment by simonsan** [comment]
We reworked and improved the `RusticError` API in https://github.com/rustic-rs/rustic_core/releases/tag/rustic_core-v0.6.0

In case there are still problems, feel free to reopen.
