### ISSUE TITLE
`RepositoryOptions, SnapshotOptions`  many data structures  miss intelligent prompts

### ISSUE THREAD

**Issue by zhuxiujia** [rustic-rs/rustic_core#241]
![image](https://github.com/user-attachments/assets/cc7d43c5-49da-41c4-b2f3-05344a40b3de)

Is there any way to make it prompt normally in RustRover?

**Comment by aawsome** [comment]
@zhuxiujia can you please specify what the problem with these structures is? I don't know RustRover...

**Comment by simonsan** [comment]
Going to close this, due to uncertainty if that really affects `rustic_core` or `RustRover`. Please feel free to reopen in case there are any new clarifications.
