### ISSUE TITLE
Release new version of rustic_backend

### ISSUE THREAD

**Issue by bothra90** [rustic-rs/rustic_core#330]
It looks like the latest version of rustic_core (`0.5.3`) is not compatible with the latest available version of rustic_backend (`0.4.1`) on crates.io. Can we get the latest version for backend uploaded to crates.io as well please?

**Comment by simonsan** [comment]
Hey there, can you please show the error/warning that you get. The newest version of rustic_backend is already available on crates.io.

**Comment by simonsan** [comment]
I can't reproduce this, if you can, please post an error message you get and reopen this issue. 👍🏽
